import type { AudienceSegment, BroadcastItem } from "@/components/shared";
import type { IncomingOrder } from "@/components/shared/IncomingOrders";
import type { Partner } from "@/components/shared/Partnerships";
import type { Product } from "@/components/shared/ProductManagement";

// ============================================================================
// BROADCAST / PROMOTIONS DATA
// ============================================================================

export const retailerSegments: AudienceSegment[] = [
  {
    id: "new-customers",
    name: "New Customers",
    count: 45,
    description: "Retailers with less than 3 orders",
  },
  {
    id: "premium",
    name: "Premium Retailers",
    count: 28,
    description: "Retailers with > ETB 100K monthly spend",
  },
  {
    id: "frequent",
    name: "Frequent Buyers",
    count: 62,
    description: "Retailers with 10+ orders per month",
  },
  {
    id: "inactive",
    name: "Inactive (30+ days)",
    count: 31,
    description: "No orders in last 30 days",
  },
];

export const promotions: BroadcastItem[] = [
  {
    id: "PROMO-001",
    title: "Flash Sale: 20% Off Selected Electronics",
    description: "Get 20% discount on all electronics. Limited time offer!",
    type: "discount",
    discountType: "percentage",
    discountValue: 20,
    minOrder: 5000,
    maxDiscount: 5000,
    startDate: "2026-02-15T00:00:00",
    endDate: "2026-02-18T23:59:59",
    status: "scheduled",
    createdAt: "2026-02-10T10:30:00",
    createdBy: "Abebe Kebede",
    sentCount: 0,
    viewedCount: 0,
    redeemedCount: 0,
    code: "FLASH20",
    priority: "high",
    targetAudience: "all",
  },
  {
    id: "PROMO-002",
    title: "Buy 2 Get 1 Free - White Teff Flour",
    description: "Purchase 2kg of White Teff Flour and get 1kg free!",
    type: "bogo",
    startDate: "2026-02-10T00:00:00",
    endDate: "2026-02-28T23:59:59",
    status: "active",
    createdAt: "2026-02-08T14:15:00",
    createdBy: "Abebe Kebede",
    sentCount: 245,
    viewedCount: 189,
    redeemedCount: 67,
    priority: "medium",
    targetAudience: "all",
  },
  {
    id: "PROMO-003",
    title: "Free Shipping on Orders Over ETB 10,000",
    description: "Enjoy free shipping on all orders above ETB 10,000",
    type: "free-shipping",
    minOrder: 10000,
    startDate: "2026-02-01T00:00:00",
    endDate: "2026-02-29T23:59:59",
    status: "active",
    createdAt: "2026-01-28T09:00:00",
    createdBy: "Abebe Kebede",
    sentCount: 567,
    viewedCount: 432,
    redeemedCount: 156,
    priority: "medium",
    targetAudience: "all",
  },
  {
    id: "PROMO-004",
    title: "New Customer Special: 15% Off First Order",
    description: "First-time buyers get 15% discount on their first purchase",
    type: "discount",
    discountType: "percentage",
    discountValue: 15,
    startDate: "2026-02-01T00:00:00",
    endDate: "2026-03-31T23:59:59",
    status: "active",
    createdAt: "2026-01-30T11:45:00",
    createdBy: "Abebe Kebede",
    sentCount: 89,
    viewedCount: 67,
    redeemedCount: 23,
    code: "WELCOME15",
    priority: "high",
    targetAudience: "segment",
    audienceSegments: ["new-customers"],
  },
  {
    id: "PROMO-005",
    title: "Clearance: Construction Materials",
    description: "Up to 30% off on selected construction materials",
    type: "clearance",
    discountType: "percentage",
    discountValue: 30,
    startDate: "2026-02-05T00:00:00",
    endDate: "2026-02-20T23:59:59",
    status: "active",
    createdAt: "2026-02-03T13:20:00",
    createdBy: "Abebe Kebede",
    sentCount: 134,
    viewedCount: 98,
    redeemedCount: 34,
    priority: "high",
    targetAudience: "all",
  },
  {
    id: "PROMO-006",
    title: "Bulk Purchase Discount - Coffee",
    description: "10% off on bulk coffee orders (50kg+)",
    type: "discount",
    discountType: "percentage",
    discountValue: 10,
    minOrder: 50,
    startDate: "2026-02-01T00:00:00",
    endDate: "2026-02-28T23:59:59",
    status: "active",
    createdAt: "2026-01-29T16:00:00",
    createdBy: "Abebe Kebede",
    sentCount: 78,
    viewedCount: 56,
    redeemedCount: 21,
    priority: "low",
    targetAudience: "all",
  },
  {
    id: "PROMO-007",
    title: "Loyalty Bonus: 5% Cashback",
    description: "5% cashback on all orders for premium retailers",
    type: "discount",
    discountType: "percentage",
    discountValue: 5,
    startDate: "2026-02-15T00:00:00",
    endDate: "2026-03-15T23:59:59",
    status: "draft",
    createdAt: "2026-02-12T09:30:00",
    createdBy: "Abebe Kebede",
    sentCount: 0,
    viewedCount: 0,
    redeemedCount: 0,
    priority: "medium",
    targetAudience: "segment",
    audienceSegments: ["premium"],
  },
  {
    id: "PROMO-008",
    title: "Holiday Special: Independence Day Sale",
    description: "Special discounts for Ethiopian Independence Day",
    type: "discount",
    discountType: "percentage",
    discountValue: 25,
    startDate: "2026-03-01T00:00:00",
    endDate: "2026-03-07T23:59:59",
    status: "draft",
    createdAt: "2026-02-11T14:45:00",
    createdBy: "Abebe Kebede",
    sentCount: 0,
    viewedCount: 0,
    redeemedCount: 0,
    priority: "low",
    targetAudience: "all",
  },
];

// ============================================================================
// PRODUCT MANAGEMENT DATA
// ============================================================================

export const categories = [
  "Food",
  "Grains",
  "Beverages",
  "Construction",
  "Textiles",
  "Furniture",
  "Stationery",
  "Household",
];

export const suppliers = [
  { id: 101, name: "Ethiopia Coffee Export" },
  { id: 102, name: "Adama Wholesalers" },
  { id: 103, name: "Ethiopian Textile" },
  { id: 104, name: "Bahir Dar Honey" },
  { id: 105, name: "Mekelle Steel" },
  { id: 106, name: "Adama Plastics" },
  { id: 107, name: "Ethiopia Agri" },
  { id: 108, name: "Mugher Cement" },
];

export const initialProducts: Product[] = [
  {
    id: 1,
    name: "White Teff Flour",
    sku: "TFF-001",
    category: "Grains",
    subcategory: "Teff",
    price: 120,
    unit: "kg",
    minOrder: 25,
    stock: 1250,
    reserved: 450,
    available: 800,
    supplier: "Ethiopia Agri",
    supplierId: 107,
    status: "active",
    verified: true,
    image: null,
    rating: 4.7,
    reviews: 95,
    sales: 3450,
    revenue: 414000,
    lastOrdered: "2026-02-10",
    tags: ["Gluten-Free", "Organic", "Bulk"],
    description:
      "High-quality white teff flour, gluten-free, perfect for injera and baking.",
  },
  {
    id: 2,
    name: "Soybean Oil",
    sku: "OIL-002",
    category: "Food",
    subcategory: "Oils",
    price: 180,
    unit: "liter",
    minOrder: 50,
    stock: 2800,
    reserved: 600,
    available: 2200,
    supplier: "Adama Wholesalers",
    supplierId: 102,
    status: "active",
    verified: true,
    image: null,
    rating: 4.6,
    reviews: 89,
    sales: 5200,
    revenue: 936000,
    lastOrdered: "2026-02-09",
    tags: ["Cooking", "Refined", "Bulk"],
    description: "Refined soybean oil, 5L bottles. Ethiopian standard.",
  },
  {
    id: 3,
    name: "Tomato Paste",
    sku: "TOM-003",
    category: "Food",
    subcategory: "Canned Goods",
    price: 85,
    unit: "can",
    minOrder: 100,
    stock: 3500,
    reserved: 800,
    available: 2700,
    supplier: "Ethiopia Agri",
    supplierId: 107,
    status: "active",
    verified: true,
    image: null,
    rating: 4.4,
    reviews: 73,
    sales: 8900,
    revenue: 756500,
    lastOrdered: "2026-02-08",
    tags: ["Bulk", "Canned"],
    description:
      "Double-concentrated tomato paste, 500g cans. Ethiopian grown tomatoes.",
  },
  {
    id: 4,
    name: "Yirgacheffe Coffee",
    sku: "COF-004",
    category: "Beverages",
    subcategory: "Coffee",
    price: 450,
    unit: "kg",
    minOrder: 10,
    stock: 2450,
    reserved: 300,
    available: 2150,
    supplier: "Ethiopia Coffee Export",
    supplierId: 101,
    status: "active",
    verified: true,
    image: null,
    rating: 4.9,
    reviews: 128,
    sales: 1800,
    revenue: 810000,
    lastOrdered: "2026-02-07",
    tags: ["Premium", "Organic", "Fair Trade"],
    description: "Premium Yirgacheffe coffee beans, washed process, grade 1.",
  },
  {
    id: 5,
    name: "Macadamia Nuts",
    sku: "NUT-005",
    category: "Food",
    subcategory: "Nuts",
    price: 650,
    unit: "kg",
    minOrder: 20,
    stock: 780,
    reserved: 120,
    available: 660,
    supplier: "Ethiopia Coffee Export",
    supplierId: 101,
    status: "active",
    verified: true,
    image: null,
    rating: 4.9,
    reviews: 56,
    sales: 450,
    revenue: 292500,
    lastOrdered: "2026-02-06",
    tags: ["Premium", "Snacks"],
    description: "Premium macadamia nuts, roasted and salted. Export quality.",
  },
  {
    id: 6,
    name: "Plastic Chairs",
    sku: "CHR-006",
    category: "Furniture",
    subcategory: "Chairs",
    price: 450,
    unit: "piece",
    minOrder: 50,
    stock: 1200,
    reserved: 200,
    available: 1000,
    supplier: "Adama Plastics",
    supplierId: 106,
    status: "active",
    verified: false,
    image: null,
    rating: 4.3,
    reviews: 29,
    sales: 850,
    revenue: 382500,
    lastOrdered: "2026-02-05",
    tags: ["Household", "Stackable"],
    description: "Durable plastic chairs, stackable, various colors available.",
  },
  {
    id: 7,
    name: "Notebooks",
    sku: "NB-007",
    category: "Stationery",
    subcategory: "Notebooks",
    price: 45,
    unit: "piece",
    minOrder: 100,
    stock: 5600,
    reserved: 1200,
    available: 4400,
    supplier: "Adama Wholesalers",
    supplierId: 102,
    status: "active",
    verified: true,
    image: null,
    rating: 4.5,
    reviews: 112,
    sales: 12500,
    revenue: 562500,
    lastOrdered: "2026-02-04",
    tags: ["School", "Bulk"],
    description: "70-page notebooks, ruled, soft cover. School supply quality.",
  },
  {
    id: 8,
    name: "Cotton Fabric",
    sku: "FAB-008",
    category: "Textiles",
    subcategory: "Fabric",
    price: 320,
    unit: "meter",
    minOrder: 50,
    stock: 1800,
    reserved: 350,
    available: 1450,
    supplier: "Ethiopian Textile",
    supplierId: 103,
    status: "inactive",
    verified: false,
    image: null,
    rating: 4.5,
    reviews: 67,
    sales: 2300,
    revenue: 736000,
    lastOrdered: "2026-02-03",
    tags: ["Eco-Friendly", "Fabric"],
    description: "100% cotton fabric, 120 GSM, available in various colors.",
  },
  {
    id: 9,
    name: "Pure Honey",
    sku: "HON-009",
    category: "Food",
    subcategory: "Honey",
    price: 280,
    unit: "jar",
    minOrder: 12,
    stock: 890,
    reserved: 150,
    available: 740,
    supplier: "Bahir Dar Honey",
    supplierId: 104,
    status: "active",
    verified: true,
    image: null,
    rating: 4.8,
    reviews: 42,
    sales: 620,
    revenue: 173600,
    lastOrdered: "2026-02-02",
    tags: ["Organic", "Raw"],
    description: "100% pure white honey, raw and unfiltered.",
  },
  {
    id: 10,
    name: "Steel Rebars",
    sku: "STL-010",
    category: "Construction",
    subcategory: "Steel",
    price: 8500,
    unit: "ton",
    minOrder: 5,
    stock: 320,
    reserved: 50,
    available: 270,
    supplier: "Mekelle Steel",
    supplierId: 105,
    status: "active",
    verified: true,
    image: null,
    rating: 4.6,
    reviews: 38,
    sales: 180,
    revenue: 1530000,
    lastOrdered: "2026-02-01",
    tags: ["Industrial", "Construction"],
    description:
      "High-tensile steel rebars, 12mm-32mm diameter. ASTM standards.",
  },
  {
    id: 11,
    name: "Cement",
    sku: "CEM-011",
    category: "Construction",
    subcategory: "Cement",
    price: 620,
    unit: "bag",
    minOrder: 100,
    stock: 4200,
    reserved: 800,
    available: 3400,
    supplier: "Mugher Cement",
    supplierId: 108,
    status: "active",
    verified: true,
    image: null,
    rating: 4.7,
    reviews: 214,
    sales: 5600,
    revenue: 3472000,
    lastOrdered: "2026-01-30",
    tags: ["Industrial", "Bulk"],
    description: "Portland cement, 50kg bags. Grade 42.5R.",
  },
  {
    id: 12,
    name: "Pasta",
    sku: "PAS-012",
    category: "Food",
    subcategory: "Pasta",
    price: 95,
    unit: "kg",
    minOrder: 50,
    stock: 150,
    reserved: 80,
    available: 70,
    supplier: "Adama Wholesalers",
    supplierId: 102,
    status: "active",
    verified: true,
    image: null,
    rating: 4.2,
    reviews: 31,
    sales: 420,
    revenue: 39900,
    lastOrdered: "2026-01-28",
    tags: ["Food", "Bulk"],
    description: "Durum wheat pasta, various shapes.",
  },
];
export const incomingOrders: IncomingOrder[] = [
  {
    id: "ORD-2026-0245",
    customerId: 201,
    customerName: "ABC Retail Shop",
    customerContact: "Hidaya Nurmeika",
    customerPhone: "+251 91 234 5678",
    customerLocation: "Adama, Bole Road",
    orderDate: "2026-02-12T09:30:00",
    requestedDelivery: "2026-02-15",
    items: [
      {
        name: "White Teff Flour",
        sku: "TFF-001",
        quantity: 25,
        unit: "kg",
        price: 120,
        total: 3000,
      },
      {
        name: "Soybean Oil",
        sku: "OIL-002",
        quantity: 30,
        unit: "liter",
        price: 180,
        total: 5400,
      },
      {
        name: "Tomato Paste",
        sku: "TOM-003",
        quantity: 50,
        unit: "can",
        price: 85,
        total: 4250,
      },
    ],
    subtotal: 12650,
    shipping: 350,
    tax: 1897.5,
    total: 14897.5,
    status: "pending",
    paymentStatus: "pending",
    paymentMethod: "Credit",
    priority: "high",
    notes: "Urgent delivery requested. Business running low on stock.",
    customerRating: 4.8,
    previousOrders: 12,
  },
  {
    id: "ORD-2026-0244",
    customerId: 202,
    customerName: "Mega Mart",
    customerContact: "Tsegaye Mulugeta",
    customerPhone: "+251 91 876 5432",
    customerLocation: "Addis Ababa, Bole",
    orderDate: "2026-02-12T08:15:00",
    requestedDelivery: "2026-02-16",
    items: [
      {
        name: "Yirgacheffe Coffee",
        sku: "COF-004",
        quantity: 15,
        unit: "kg",
        price: 450,
        total: 6750,
      },
      {
        name: "Macadamia Nuts",
        sku: "NUT-005",
        quantity: 20,
        unit: "kg",
        price: 650,
        total: 13000,
      },
      {
        name: "Pure Honey",
        sku: "HON-009",
        quantity: 24,
        unit: "jar",
        price: 280,
        total: 6720,
      },
      {
        name: "White Teff Flour",
        sku: "TFF-001",
        quantity: 50,
        unit: "kg",
        price: 120,
        total: 6000,
      },
    ],
    subtotal: 32470,
    shipping: 800,
    tax: 4870.5,
    total: 38140.5,
    status: "pending",
    paymentStatus: "pending",
    paymentMethod: "Mobile Banking",
    priority: "high",
    notes: "New customer, first order. Requesting credit terms.",
    customerRating: null,
    previousOrders: 0,
  },
  {
    id: "ORD-2026-0243",
    customerId: 203,
    customerName: "City Supermarket",
    customerContact: "Almaz Worku",
    customerPhone: "+251 92 345 6789",
    customerLocation: "Adama, Awash Sefer",
    orderDate: "2026-02-11T15:45:00",
    requestedDelivery: "2026-02-14",
    items: [
      {
        name: "Cement",
        sku: "CEM-011",
        quantity: 100,
        unit: "bag",
        price: 620,
        total: 62000,
      },
      {
        name: "Steel Rebars",
        sku: "STL-010",
        quantity: 5,
        unit: "ton",
        price: 8500,
        total: 42500,
      },
    ],
    subtotal: 104500,
    shipping: 2500,
    tax: 15675,
    total: 122675,
    status: "processing",
    paymentStatus: "approved",
    paymentMethod: "Credit",
    priority: "medium",
    notes: "Construction materials for new store branch.",
    customerRating: 4.7,
    previousOrders: 8,
  },
  {
    id: "ORD-2026-0242",
    customerId: 204,
    customerName: "Addis Mart",
    customerContact: "Biruk Haile",
    customerPhone: "+251 93 456 7890",
    customerLocation: "Addis Ababa, Merkato",
    orderDate: "2026-02-11T11:20:00",
    requestedDelivery: "2026-02-13",
    items: [
      {
        name: "Plastic Chairs",
        sku: "CHR-006",
        quantity: 100,
        unit: "piece",
        price: 450,
        total: 45000,
      },
      {
        name: "Notebooks",
        sku: "NB-007",
        quantity: 500,
        unit: "piece",
        price: 45,
        total: 22500,
      },
    ],
    subtotal: 67500,
    shipping: 1200,
    tax: 10125,
    total: 78825,
    status: "approved",
    paymentStatus: "paid",
    paymentMethod: "Credit",
    priority: "low",
    notes: "Ready for pickup. Customer will arrange transport.",
    customerRating: 4.9,
    previousOrders: 24,
  },
  {
    id: "ORD-2026-0241",
    customerId: 205,
    customerName: "Bole Superstore",
    customerContact: "Meron Assefa",
    customerPhone: "+251 94 567 8901",
    customerLocation: "Addis Ababa, Bole",
    orderDate: "2026-02-10T14:30:00",
    requestedDelivery: "2026-02-12",
    items: [
      {
        name: "Cotton Fabric",
        sku: "FAB-008",
        quantity: 200,
        unit: "meter",
        price: 320,
        total: 64000,
      },
      {
        name: "Yirgacheffe Coffee",
        sku: "COF-004",
        quantity: 10,
        unit: "kg",
        price: 450,
        total: 4500,
      },
    ],
    subtotal: 68500,
    shipping: 1500,
    tax: 10275,
    total: 80275,
    status: "shipped",
    paymentStatus: "paid",
    paymentMethod: "Mobile Banking",
    priority: "medium",
    notes: "Shipped via Express Delivery. Tracking: TRK-7885-02",
    trackingNumber: "TRK-7885-02",
    driver: "Abebe Kebede",
    driverId: 301,
    customerRating: 4.6,
    previousOrders: 15,
  },
  {
    id: "ORD-2026-0240",
    customerId: 206,
    customerName: "Hawassa Wholesale",
    customerContact: "Dawit Tadesse",
    customerPhone: "+251 95 678 9012",
    customerLocation: "Hawassa, Main Market",
    orderDate: "2026-02-09T10:00:00",
    requestedDelivery: "2026-02-11",
    items: [
      {
        name: "White Teff Flour",
        sku: "TFF-001",
        quantity: 200,
        unit: "kg",
        price: 120,
        total: 24000,
      },
      {
        name: "Soybean Oil",
        sku: "OIL-002",
        quantity: 100,
        unit: "liter",
        price: 180,
        total: 18000,
      },
      {
        name: "Tomato Paste",
        sku: "TOM-003",
        quantity: 200,
        unit: "can",
        price: 85,
        total: 17000,
      },
    ],
    subtotal: 59000,
    shipping: 1800,
    tax: 8850,
    total: 69650,
    status: "delivered",
    paymentStatus: "paid",
    paymentMethod: "Credit",
    priority: "low",
    notes: "Delivered and signed by Dawit Tadesse.",
    deliveredDate: "2026-02-11",
    customerRating: 4.8,
    previousOrders: 32,
  },
  {
    id: "ORD-2026-0239",
    customerId: 207,
    customerName: "Dire Dava Traders",
    customerContact: "Fatuma Ahmed",
    customerPhone: "+251 96 789 0123",
    customerLocation: "Dire Dawa, Industrial Zone",
    orderDate: "2026-02-08T13:45:00",
    requestedDelivery: "2026-02-12",
    items: [
      {
        name: "Cement",
        sku: "CEM-011",
        quantity: 200,
        unit: "bag",
        price: 620,
        total: 124000,
      },
      {
        name: "Steel Rebars",
        sku: "STL-010",
        quantity: 8,
        unit: "ton",
        price: 8500,
        total: 68000,
      },
    ],
    subtotal: 192000,
    shipping: 3500,
    tax: 28800,
    total: 224300,
    status: "cancelled",
    paymentStatus: "refunded",
    paymentMethod: "Bank Transfer",
    priority: "medium",
    notes: "Cancelled by customer - found alternative supplier.",
    cancellationReason: "Customer requested cancellation",
    cancelledDate: "2026-02-09",
    customerRating: null,
    previousOrders: 5,
  },
];
// ============================================================================
// PRODUCT CATALOG DATA (Factory Products)
// ============================================================================

export const factoryProducts = [
  {
    id: 1001,
    name: "Portland Cement",
    supplierId: 501,
    supplierName: "Mugher Cement",
    category: "Construction",
    subcategory: "Cement",
    price: 520,
    unit: "bag",
    minOrder: 100,
    maxOrder: 5000,
    stock: 15000,
    rating: 4.7,
    reviews: 312,
    location: "Addis Ababa",
    deliveryTime: "2-3 days",
    verified: true,
    description:
      "Premium Portland cement, 50kg bags. Grade 42.5R. Suitable for all construction applications.",
    tags: ["Industrial", "Bulk", "High Quality"],
    volumeDiscount: "5% off on 1000+ bags",
    leadTime: "2-3 days",
    paymentTerms: ["Credit", "Mobile", "Bank Transfer"],
  },
  {
    id: 1002,
    name: "Steel Rebars 12mm",
    supplierId: 502,
    supplierName: "Mekelle Steel",
    category: "Construction",
    subcategory: "Steel",
    price: 7500,
    unit: "ton",
    minOrder: 5,
    maxOrder: 50,
    stock: 450,
    rating: 4.6,
    reviews: 189,
    location: "Mekelle",
    deliveryTime: "5-7 days",
    verified: true,
    description:
      "High-tensile steel rebars, 12mm diameter. ASTM A615 Grade 60 standard.",
    tags: ["Industrial", "Steel", "Construction"],
    volumeDiscount: "3% off on 20+ tons",
    leadTime: "5-7 days",
    paymentTerms: ["Credit", "Bank Transfer"],
  },
  {
    id: 1003,
    name: "Cotton Fabric Rolls",
    supplierId: 503,
    supplierName: "Ethiopian Textile",
    category: "Textiles",
    subcategory: "Fabric",
    price: 280,
    unit: "meter",
    minOrder: 100,
    maxOrder: 10000,
    stock: 25000,
    rating: 4.5,
    reviews: 156,
    location: "Addis Ababa",
    deliveryTime: "3-5 days",
    verified: false,
    description:
      "100% cotton fabric, 120 GSM, 150cm width. Available in white and natural colors.",
    tags: ["Textiles", "Fabric", "Cotton"],
    volumeDiscount: "10% off on 1000+ meters",
    leadTime: "3-5 days",
    paymentTerms: ["Credit", "Mobile", "Cash"],
  },
  {
    id: 1004,
    name: "Yirgacheffe Coffee Beans",
    supplierId: 504,
    supplierName: "Ethiopia Coffee Export",
    category: "Beverages",
    subcategory: "Coffee",
    price: 380,
    unit: "kg",
    minOrder: 50,
    maxOrder: 2000,
    stock: 8500,
    rating: 4.9,
    reviews: 425,
    location: "Addis Ababa",
    deliveryTime: "2-3 days",
    verified: true,
    description:
      "Grade 1 Yirgacheffe coffee beans, washed process. Floral and citrus notes.",
    tags: ["Coffee", "Premium", "Organic"],
    volumeDiscount: "8% off on 500+ kg",
    leadTime: "2-3 days",
    paymentTerms: ["Credit", "Mobile", "Bank Transfer"],
  },
  {
    id: 1005,
    name: "White Teff Grain",
    supplierId: 505,
    supplierName: "Ethiopia Agri",
    category: "Grains",
    subcategory: "Teff",
    price: 95,
    unit: "kg",
    minOrder: 200,
    maxOrder: 10000,
    stock: 45000,
    rating: 4.8,
    reviews: 278,
    location: "Adama",
    deliveryTime: "2-4 days",
    verified: true,
    description:
      "Premium white teff grain, certified organic. High yield, excellent for injera.",
    tags: ["Grains", "Teff", "Organic"],
    volumeDiscount: "12% off on 1000+ kg",
    leadTime: "2-4 days",
    paymentTerms: ["Credit", "Mobile", "Cash"],
  },
  {
    id: 1006,
    name: "Soybean Oil - Bulk",
    supplierId: 506,
    supplierName: "Adama Oil",
    category: "Food",
    subcategory: "Oils",
    price: 145,
    unit: "liter",
    minOrder: 500,
    maxOrder: 20000,
    stock: 35000,
    rating: 4.6,
    reviews: 203,
    location: "Adama",
    deliveryTime: "3-5 days",
    verified: true,
    description:
      "Refined soybean oil, food grade. Packed in 20L jerry cans for bulk buyers.",
    tags: ["Oil", "Cooking", "Bulk"],
    volumeDiscount: "7% off on 2000+ liters",
    leadTime: "3-5 days",
    paymentTerms: ["Credit", "Bank Transfer"],
  },
  {
    id: 1007,
    name: "Plastic Granules",
    supplierId: 507,
    supplierName: "Adama Plastics",
    category: "Raw Materials",
    subcategory: "Plastics",
    price: 85,
    unit: "kg",
    minOrder: 500,
    maxOrder: 10000,
    stock: 28000,
    rating: 4.4,
    reviews: 98,
    location: "Adama",
    deliveryTime: "3-4 days",
    verified: false,
    description:
      "Polypropylene granules for injection molding. Food-grade quality.",
    tags: ["Plastics", "Raw Materials", "Industrial"],
    volumeDiscount: "5% off on 2000+ kg",
    leadTime: "3-4 days",
    paymentTerms: ["Mobile", "Cash", "Bank Transfer"],
  },
  {
    id: 1008,
    name: "Macadamia Nuts",
    supplierId: 504,
    supplierName: "Ethiopia Coffee Export",
    category: "Food",
    subcategory: "Nuts",
    price: 580,
    unit: "kg",
    minOrder: 100,
    maxOrder: 2000,
    stock: 3200,
    rating: 4.9,
    reviews: 167,
    location: "Addis Ababa",
    deliveryTime: "2-3 days",
    verified: true,
    description:
      "Premium macadamia nuts, roasted and lightly salted. Export quality.",
    tags: ["Nuts", "Premium", "Snacks"],
    volumeDiscount: "10% off on 500+ kg",
    leadTime: "2-3 days",
    paymentTerms: ["Credit", "Mobile", "Bank Transfer"],
  },
];

// Categories for filter
export const distributorCategories = [
  "All Categories",
  "Construction",
  "Textiles",
  "Beverages",
  "Grains",
  "Food",
  "Raw Materials",
];

// Locations for filter
export const distributorLocations = [
  "All Locations",
  "Addis Ababa",
  "Adama",
  "Mekelle",
  "Bahir Dar",
  "Hawassa",
  "Dire Dawa",
];

// ============================================================================
// SUPPLIER PARTNERSHIPS DATA
// ============================================================================

export const supplierPartners: Partner[] = [
  {
    id: 501,
    name: "Mugher Cement",
    type: "factory",                    // ✅ Must be one of the allowed literal types
    category: ["Construction", "Cement"],
    location: "Addis Ababa",
    region: "Central",
    established: "2005",
    verified: true,
    tier: "platinum",                    // ✅ Must be one of the allowed tier types
    rating: 4.8,
    totalOrders: 245,
    totalValue: 12450000,
    avgOrderValue: 50816,
    onTimeDelivery: 98.5,
    qualityRating: 4.7,
    communicationRating: 4.9,
    responseTime: "< 1 hour",
    leadTime: "2-3 days",
    paymentTerms: "Net 30",
    creditLimit: 2000000,
    creditUsed: 850000,
    contractStart: "2024-01-01",
    contractEnd: "2026-12-31",
    contractStatus: "active",            // ✅ Must be one of the allowed status types
    products: 8,
    categories: ["Cement", "Construction"],
    contactPerson: "Tadesse Haile",
    contactPhone: "+251 11 234 5678",
    contactEmail: "tadesse.h@mugher.com",
    lastOrderDate: "2026-02-10",
    nextDeliveryDate: "2026-02-18",
    issues: 0,
  },
  {
    id: 502,
    name: "Mekelle Steel",
    type: "factory",
    category: ["Construction", "Steel"],
    location: "Mekelle",
    region: "Northern",
    established: "2012",
    verified: true,
    tier: "gold",
    rating: 4.6,
    totalOrders: 178,
    totalValue: 8900000,
    avgOrderValue: 50000,
    onTimeDelivery: 96.8,
    qualityRating: 4.6,
    communicationRating: 4.5,
    responseTime: "< 2 hours",
    leadTime: "5-7 days",
    paymentTerms: "Net 30",
    creditLimit: 1500000,
    creditUsed: 620000,
    contractStart: "2024-03-15",
    contractEnd: "2026-03-14",
    contractStatus: "active",
    products: 15,
    categories: ["Steel", "Rebars", "Sheets"],
    contactPerson: "Mulugeta Assefa",
    contactPhone: "+251 34 567 8901",
    contactEmail: "mulugeta.a@mekellesteel.com",
    lastOrderDate: "2026-02-09",
    nextDeliveryDate: "2026-02-23",
    issues: 1,
  },
  {
    id: 503,
    name: "Ethiopian Textile",
    type: "manufacturer",
    category: ["Textiles", "Fabric"],
    location: "Addis Ababa",
    region: "Central",
    established: "2010",
    verified: false,
    tier: "silver",
    rating: 4.3,
    totalOrders: 98,
    totalValue: 2450000,
    avgOrderValue: 25000,
    onTimeDelivery: 92.5,
    qualityRating: 4.2,
    communicationRating: 4.3,
    responseTime: "< 4 hours",
    leadTime: "3-5 days",
    paymentTerms: "Net 15",
    creditLimit: 500000,
    creditUsed: 180000,
    contractStart: "2024-06-01",
    contractEnd: "2025-12-31",
    contractStatus: "active",
    products: 45,
    categories: ["Cotton", "Fabric", "Garments"],
    contactPerson: "Hirut Desta",
    contactPhone: "+251 11 456 7890",
    contactEmail: "hirut.d@ethiotextile.com",
    lastOrderDate: "2026-02-06",
    issues: 3,
  },
  {
    id: 504,
    name: "Ethiopia Coffee Export",
    type: "processor",
    category: ["Beverages", "Coffee"],
    location: "Addis Ababa",
    region: "Central",
    established: "2015",
    verified: true,
    tier: "platinum",
    rating: 4.9,
    totalOrders: 312,
    totalValue: 7800000,
    avgOrderValue: 25000,
    onTimeDelivery: 99.2,
    qualityRating: 4.9,
    communicationRating: 4.8,
    responseTime: "< 30 minutes",
    leadTime: "2-3 days",
    paymentTerms: "Net 30",
    creditLimit: 1000000,
    creditUsed: 420000,
    contractStart: "2024-02-01",
    contractEnd: "2027-01-31",
    contractStatus: "active",
    products: 12,
    categories: ["Coffee", "Nuts", "Spices"],
    contactPerson: "Bereket Tesfaye",
    contactPhone: "+251 11 345 6789",
    contactEmail: "bereket.t@ethiopiacoffee.com",
    lastOrderDate: "2026-02-10",
    nextDeliveryDate: "2026-02-20",
    issues: 0,
  },
  {
    id: 505,
    name: "Ethiopia Agri",
    type: "processor",
    category: ["Food", "Grains"],
    location: "Adama",
    region: "Central",
    established: "2016",
    verified: true,
    tier: "gold",
    rating: 4.7,
    totalOrders: 203,
    totalValue: 5100000,
    avgOrderValue: 25123,
    onTimeDelivery: 97.8,
    qualityRating: 4.7,
    communicationRating: 4.6,
    responseTime: "< 1 hour",
    leadTime: "2-4 days",
    paymentTerms: "Net 30",
    creditLimit: 800000,
    creditUsed: 350000,
    contractStart: "2024-05-15",
    contractEnd: "2026-05-14",
    contractStatus: "active",
    products: 28,
    categories: ["Teff", "Grains", "Oils"],
    contactPerson: "Almaz Worku",
    contactPhone: "+251 22 456 7890",
    contactEmail: "almaz.w@ethiopiaagri.com",
    lastOrderDate: "2026-02-07",
    nextDeliveryDate: "2026-02-19",
    issues: 0,
  },
  {
    id: 506,
    name: "Adama Oil",
    type: "factory",
    category: ["Food", "Oils"],
    location: "Adama",
    region: "Central",
    established: "2018",
    verified: true,
    tier: "silver",
    rating: 4.5,
    totalOrders: 87,
    totalValue: 2950000,
    avgOrderValue: 33908,
    onTimeDelivery: 95.2,
    qualityRating: 4.5,
    communicationRating: 4.4,
    responseTime: "< 2 hours",
    leadTime: "3-5 days",
    paymentTerms: "Net 15",
    creditLimit: 400000,
    creditUsed: 210000,
    contractStart: "2024-08-01",
    contractEnd: "2025-12-31",
    contractStatus: "expiring",
    products: 6,
    categories: ["Soybean Oil", "Cooking Oil"],
    contactPerson: "Kebede Desta",
    contactPhone: "+251 22 567 8901",
    contactEmail: "kebede.d@adamaoil.com",
    lastOrderDate: "2026-02-05",
    issues: 1,
  },
  {
    id: 507,
    name: "Adama Plastics",
    type: "manufacturer",
    category: ["Household", "Plastics"],
    location: "Adama",
    region: "Central",
    established: "2017",
    verified: false,
    tier: "bronze",
    rating: 4.2,
    totalOrders: 56,
    totalValue: 1250000,
    avgOrderValue: 22321,
    onTimeDelivery: 91.5,
    qualityRating: 4.1,
    communicationRating: 4.2,
    responseTime: "< 5 hours",
    leadTime: "3-4 days",
    paymentTerms: "Net 15",
    creditLimit: 200000,
    creditUsed: 95000,
    contractStart: "2024-09-01",
    contractEnd: "2025-12-31",
    contractStatus: "expiring",
    products: 35,
    categories: ["Plastic Chairs", "Household"],
    contactPerson: "Solomon Ayele",
    contactPhone: "+251 22 678 9012",
    contactEmail: "solomon.a@adamaplastics.com",
    lastOrderDate: "2026-02-04",
    issues: 2,
  },
  {
    id: 508,
    name: "Bahir Dar Honey",
    type: "processor",
    category: ["Food", "Honey"],
    location: "Bahir Dar",
    region: "Amhara",
    established: "2019",
    verified: true,
    tier: "silver",
    rating: 4.8,
    totalOrders: 42,
    totalValue: 890000,
    avgOrderValue: 21190,
    onTimeDelivery: 98.9,
    qualityRating: 4.8,
    communicationRating: 4.7,
    responseTime: "< 3 hours",
    leadTime: "2-4 days",
    paymentTerms: "Net 15",
    creditLimit: 300000,
    creditUsed: 120000,
    contractStart: "2024-10-01",
    contractEnd: "2025-12-31",
    contractStatus: "expiring",
    products: 8,
    categories: ["Honey", "Organic"],
    contactPerson: "Tigist Haile",
    contactPhone: "+251 58 234 5678",
    contactEmail: "tigist.h@bahirdarhoney.com",
    lastOrderDate: "2026-02-02",
    issues: 0,
  },
];