// ============================================================================
// BROADCAST / ANNOUNCEMENTS DATA
// ============================================================================

import type { AudienceSegment, BroadcastItem } from "@/components/shared/Broadcast";
import type { IncomingOrder } from "@/features/order/IncomingOrders";

export const distributorSegments: AudienceSegment[] = [
  {
    id: "premium-distributors",
    name: "Premium Distributors",
    count: 18,
    description: "Distributors with > ETB 500K monthly orders",
  },
  {
    id: "new-distributors",
    name: "New Partners",
    count: 12,
    description: "Distributors joined in last 3 months",
  },
  {
    id: "international",
    name: "International",
    count: 7,
    description: "Export distributors",
  },
];

export const announcements: BroadcastItem[] = [
  // Add your announcements data here
];

// ============================================================================
// PRODUCT MANAGEMENT DATA
// ============================================================================

export const categories = [
  "Construction",
  "Beverages",
  "Food",
  "Textiles",
  "Raw Materials",
];

export const factoryProducts = [
  {
    id: 1001,
    name: "Portland Cement",
    sku: "CEM-011",
    category: "Construction",
    subcategory: "Cement",
    price: 520,
    unit: "bag",
    minOrder: 100,
    stock: 15000,
    reserved: 2500,
    available: 12500,
    status: "active",
    verified: true,
    image: null,
    rating: 4.7,
    reviews: 312,
    sales: 12500,
    revenue: 6500000,
    lastOrdered: "2026-02-10",
    tags: ["Industrial", "Bulk", "High Quality"],
    description: "Premium Portland cement, 50kg bags. Grade 42.5R.",
    // Supplier fields are optional, so they can be omitted for factory
  },
  {
    id: 1002,
    name: "Steel Rebars 12mm",
    sku: "STL-010",
    category: "Construction",
    subcategory: "Steel",
    price: 7500,
    unit: "ton",
    minOrder: 5,
    stock: 450,
    reserved: 80,
    available: 370,
    status: "active",
    verified: true,
    image: null,
    rating: 4.6,
    reviews: 189,
    sales: 230,
    revenue: 1725000,
    lastOrdered: "2026-02-09",
    tags: ["Industrial", "Steel", "Construction"],
    description: "High-tensile steel rebars, 12mm diameter. ASTM A615 Grade 60.",
  },
  {
    id: 1004,
    name: "Yirgacheffe Coffee",
    sku: "COF-004",
    category: "Beverages",
    subcategory: "Coffee",
    price: 380,
    unit: "kg",
    minOrder: 50,
    stock: 8500,
    reserved: 1200,
    available: 7300,
    status: "active",
    verified: true,
    image: null,
    rating: 4.9,
    reviews: 425,
    sales: 5200,
    revenue: 1976000,
    lastOrdered: "2026-02-08",
    tags: ["Coffee", "Premium", "Organic"],
    description: "Grade 1 Yirgacheffe coffee beans, washed process.",
  },
  {
    id: 1005,
    name: "White Teff Grain",
    sku: "GRN-002",
    category: "Food",
    subcategory: "Grains",
    price: 95,
    unit: "kg",
    minOrder: 200,
    stock: 45000,
    reserved: 8000,
    available: 37000,
    status: "active",
    verified: true,
    image: null,
    rating: 4.8,
    reviews: 278,
    sales: 25000,
    revenue: 2375000,
    lastOrdered: "2026-02-07",
    tags: ["Grains", "Teff", "Organic"],
    description: "Premium white teff grain, certified organic.",
  },
  
];
export const factoryOrders: IncomingOrder[] = [
  {
    id: "FPO-2026-0125",
    customerId: 102,
    customerName: "Adama Wholesalers",
    customerContact: "Abebe Kebede",
    customerPhone: "+251 22 456 7890",
    customerLocation: "Adama",
    orderDate: "2026-02-12T10:30:00",
    requestedDelivery: "2026-02-20",
    items: [
      {
        name: "Portland Cement",
        sku: "CEM-011",
        quantity: 500,
        unit: "bags",
        price: 520,
        total: 260000,
      },
    ],
    subtotal: 260000,
    shipping: 5000,
    tax: 39000,
    total: 304000,
    status: "pending",
    paymentStatus: "pending",
    paymentMethod: "Credit",
    priority: "high",
    notes: "Urgent - needed for construction project",
    customerRating: 4.8,
    previousOrders: 12,
  },
  {
    id: "FPO-2026-0124",
    customerId: 105,
    customerName: "Mekelle Steel Distributors",
    customerContact: "Mulugeta Assefa",
    customerPhone: "+251 34 567 8901",
    customerLocation: "Mekelle",
    orderDate: "2026-02-11T14:15:00",
    requestedDelivery: "2026-02-25",
    items: [
      {
        name: "Steel Rebars 12mm",
        sku: "STL-010",
        quantity: 20,
        unit: "tons",
        price: 7500,
        total: 150000,
      },
      {
        name: "Steel Rebars 16mm",
        sku: "STL-011",
        quantity: 15,
        unit: "tons",
        price: 7400,
        total: 111000,
      },
    ],
    subtotal: 261000,
    shipping: 8000,
    tax: 39150,
    total: 308150,
    status: "processing",
    paymentStatus: "approved",
    paymentMethod: "Bank Transfer",
    priority: "medium",
    customerRating: 4.7,
    previousOrders: 8,
  },
  {
    id: "FPO-2026-0123",
    customerId: 101,
    customerName: "Ethiopia Coffee Export",
    customerContact: "Bereket Tesfaye",
    customerPhone: "+251 11 345 6789",
    customerLocation: "Addis Ababa",
    orderDate: "2026-02-10T09:45:00",
    requestedDelivery: "2026-02-22",
    items: [
      {
        name: "Yirgacheffe Coffee",
        sku: "COF-004",
        quantity: 200,
        unit: "kg",
        price: 380,
        total: 76000,
      },
      {
        name: "Macadamia Nuts",
        sku: "NUT-005",
        quantity: 150,
        unit: "kg",
        price: 580,
        total: 87000,
      },
    ],
    subtotal: 163000,
    shipping: 3500,
    tax: 24450,
    total: 190950,
    status: "approved",
    paymentStatus: "approved",
    paymentMethod: "Credit",
    priority: "medium",
    customerRating: 4.9,
    previousOrders: 15,
  },
  {
    id: "FPO-2026-0122",
    customerId: 102,
    customerName: "Adama Wholesalers",
    customerContact: "Abebe Kebede",
    customerPhone: "+251 22 456 7890",
    customerLocation: "Adama",
    orderDate: "2026-02-09T11:20:00",
    requestedDelivery: "2026-02-21",
    items: [
      {
        name: "White Teff Grain",
        sku: "GRN-002",
        quantity: 1000,
        unit: "kg",
        price: 95,
        total: 95000,
      },
    ],
    subtotal: 95000,
    shipping: 2500,
    tax: 14250,
    total: 111750,
    status: "shipped",
    paymentStatus: "paid",
    paymentMethod: "Mobile Banking",
    priority: "low",
    trackingNumber: "FTRK-0122-01",
    driver: "Tigist Haile",
    driverId: 302,
    customerRating: 4.8,
    previousOrders: 12,
  },
  {
    id: "FPO-2026-0121",
    customerId: 108,
    customerName: "Dire Dawa Trading",
    customerContact: "Fatuma Ahmed",
    customerPhone: "+251 96 789 0123",
    customerLocation: "Dire Dawa",
    orderDate: "2026-02-08T13:50:00",
    requestedDelivery: "2026-02-19",
    items: [
      {
        name: "Cotton Fabric",
        sku: "FAB-008",
        quantity: 500,
        unit: "meter",
        price: 280,
        total: 140000,
      },
    ],
    subtotal: 140000,
    shipping: 3000,
    tax: 21000,
    total: 164000,
    status: "delivered",
    paymentStatus: "paid",
    paymentMethod: "Credit",
    priority: "low",
    deliveredDate: "2026-02-17",
    customerRating: 4.5,
    previousOrders: 5,
  },
  {
    id: "FPO-2026-0120",
    customerId: 106,
    customerName: "Adama Plastics",
    customerContact: "Solomon Ayele",
    customerPhone: "+251 22 678 9012",
    customerLocation: "Adama",
    orderDate: "2026-02-07T15:30:00",
    requestedDelivery: "2026-02-18",
    items: [
      {
        name: "Plastic Granules",
        sku: "PLA-012",
        quantity: 1000,
        unit: "kg",
        price: 85,
        total: 85000,
      },
    ],
    subtotal: 85000,
    shipping: 2500,
    tax: 12750,
    total: 100250,
    status: "cancelled",
    paymentStatus: "refunded",
    paymentMethod: "Mobile Banking",
    priority: "low",
    notes: "Order cancelled due to specification change",
    cancellationReason: "Specification change requested",
    cancelledDate: "2026-02-08",
    customerRating: null,
    previousOrders: 0,
  },
];
