
// ============================================================================
// PRODUCT CATALOG DATA
// ============================================================================

import type { CatalogProduct } from "@/components/shared/ProductCatalog";

export const retailerProducts: CatalogProduct[] = [
  {
    id: 1,
    name: "Yirgacheffe Coffee",
    supplierId: 101,
    supplierName: "Ethiopia Coffee Export",
    category: "Beverages",
    subcategory: "Coffee",
    price: 450,
    unit: "kg",
    minOrder: 10,
    maxOrder: 100,
    stock: 2450,
    rating: 4.9,
    reviews: 128,
    location: "Addis Ababa",
    deliveryTime: "2-3 days",
    description: "Premium Yirgacheffe coffee beans, washed process, grade 1. Known for its floral and citrus notes.",
    tags: ["Organic", "Fair Trade", "Premium"],
  },
  {
    id: 2,
    name: "White Teff Flour",
    supplierId: 102,
    supplierName: "Adama Wholesalers",
    category: "Grains",
    subcategory: "Teff",
    price: 120,
    unit: "kg",
    minOrder: 25,
    maxOrder: 500,
    stock: 5200,
    rating: 4.7,
    reviews: 95,
    location: "Adama",
    deliveryTime: "1-2 days",
    description: "High-quality white teff flour, gluten-free, perfect for injera and baking.",
    tags: ["Gluten-Free", "Organic"],
  },
  {
    id: 3,
    name: "Cotton Fabric",
    supplierId: 103,
    supplierName: "Ethiopian Textile",
    category: "Textiles",
    subcategory: "Fabric",
    price: 320,
    unit: "meter",
    minOrder: 50,
    maxOrder: 1000,
    stock: 1800,
    rating: 4.5,
    reviews: 67,
    location: "Addis Ababa",
    deliveryTime: "3-5 days",
    description: "100% cotton fabric, 120 GSM, available in various colors. Ideal for garments.",
    tags: ["Eco-Friendly"],
  },
  {
    id: 4,
    name: "Pure Honey",
    supplierId: 104,
    supplierName: "Bahir Dar Honey",
    category: "Food",
    subcategory: "Honey",
    price: 280,
    unit: "jar",
    minOrder: 12,
    maxOrder: 200,
    stock: 890,
    rating: 4.8,
    reviews: 42,
    location: "Bahir Dar",
    deliveryTime: "2-4 days",
    
    description: "100% pure white honey, raw and unfiltered. Harvested from the forests of Bahir Dar.",
    tags: ["Organic", "Raw"],
  },
  {
    id: 5,
    name: "Steel Rebars",
    supplierId: 105,
    supplierName: "Mekelle Steel",
    category: "Construction",
    subcategory: "Steel",
    price: 8500,
    unit: "ton",
    minOrder: 5,
    maxOrder: 50,
    stock: 320,
    rating: 4.6,
    reviews: 38,
    location: "Mekelle",
    deliveryTime: "5-7 days",
    
    description: "High-tensile steel rebars, 12mm-32mm diameter. ASTM standards.",
    tags: ["Industrial"],
  },
  {
    id: 6,
    name: "Macadamia Nuts",
    supplierId: 101,
    supplierName: "Ethiopia Coffee Export",
    category: "Food",
    subcategory: "Nuts",
    price: 650,
    unit: "kg",
    minOrder: 20,
    maxOrder: 200,
    stock: 780,
    rating: 4.9,
    reviews: 56,
    location: "Addis Ababa",
    deliveryTime: "2-3 days",
    
    description: "Premium macadamia nuts, roasted and salted. Export quality.",
    tags: ["Premium", "Snacks"],
  },
  {
    id: 7,
    name: "Plastic Chairs",
    supplierId: 106,
    supplierName: "Adama Plastics",
    category: "Furniture",
    subcategory: "Chairs",
    price: 450,
    unit: "piece",
    minOrder: 50,
    maxOrder: 500,
    stock: 1200,
    rating: 4.3,
    reviews: 29,
    location: "Adama",
    deliveryTime: "3-4 days",
    
    description: "Durable plastic chairs, stackable, various colors available.",
    tags: ["Household"],
  },
  {
    id: 8,
    name: "Tomato Paste",
    supplierId: 107,
    supplierName: "Ethiopia Agri",
    category: "Food",
    subcategory: "Canned Goods",
    price: 85,
    unit: "can",
    minOrder: 100,
    maxOrder: 1000,
    stock: 3500,
    rating: 4.4,
    reviews: 73,
    location: "Adama",
    deliveryTime: "2-3 days",
    
    description: "Double-concentrated tomato paste, 500g cans. Ethiopian grown tomatoes.",
    tags: ["Bulk"],
  },
  {
    id: 9,
    name: "Notebooks",
    supplierId: 102,
    supplierName: "Adama Wholesalers",
    category: "Stationery",
    subcategory: "Notebooks",
    price: 45,
    unit: "piece",
    minOrder: 100,
    maxOrder: 1000,
    stock: 5600,
    rating: 4.5,
    reviews: 112,
    location: "Adama",
    deliveryTime: "1-2 days",
    
    description: "70-page notebooks, ruled, soft cover. School supply quality.",
    tags: ["School"],
  },
  {
    id: 10,
    name: "Cement",
    supplierId: 108,
    supplierName: "Mugher Cement",
    category: "Construction",
    subcategory: "Cement",
    price: 620,
    unit: "bag",
    minOrder: 100,
    maxOrder: 1000,
    stock: 4200,
    rating: 4.7,
    reviews: 214,
    location: "Addis Ababa",
    deliveryTime: "2-3 days",
    
    description: "Portland cement, 50kg bags. Grade 42.5R.",
    tags: ["Industrial", "Bulk"],
  },
  {
    id: 11,
    name: "Soybean Oil",
    supplierId: 102,
    supplierName: "Adama Wholesalers",
    category: "Food",
    subcategory: "Oils",
    price: 180,
    unit: "liter",
    minOrder: 50,
    maxOrder: 500,
    stock: 2800,
    rating: 4.6,
    reviews: 89,
    location: "Adama",
    deliveryTime: "1-2 days",
    
    description: "Refined soybean oil, 5L bottles. Ethiopian standard.",
    tags: ["Cooking"],
  },
  {
    id: 12,
    name: "Leather Shoes",
    supplierId: 103,
    supplierName: "Ethiopian Textile",
    category: "Footwear",
    subcategory: "Shoes",
    price: 850,
    unit: "pair",
    minOrder: 30,
    maxOrder: 200,
    stock: 450,
    rating: 4.5,
    reviews: 47,
    location: "Addis Ababa",
    deliveryTime: "4-6 days",
    
    description: "Genuine leather shoes, men's formal. Various sizes available.",
    tags: ["Leather", "Formal"],
  },
];

// Categories for filter
export const retailerCategories = [
  "All Categories",
  "Beverages",
  "Food",
  "Grains",
  "Textiles",
  "Construction",
  "Furniture",
  "Stationery",
  "Footwear",
];

// Suppliers for filter
export const retailerSuppliers = [
  { id: 101, name: "Ethiopia Coffee Export" },
  { id: 102, name: "Adama Wholesalers" },
  { id: 103, name: "Ethiopian Textile" },
  { id: 104, name: "Bahir Dar Honey" },
  { id: 105, name: "Mekelle Steel" },
  { id: 106, name: "Adama Plastics" },
  { id: 107, name: "Ethiopia Agri" },
  { id: 108, name: "Mugher Cement" },
];

// Locations for filter
export const retailerLocations = [
  "Addis Ababa",
  "Adama",
  "Bahir Dar",
  "Mekelle",
  "Hawassa",
  "Dire Dawa",
];